name: Docker Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: base-scipy
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: base-scipy/Dockerfile
          repository: dddlab/base-scipy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
      - name: base-rstudio
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: base-rstudio/Dockerfile
          repository: dddlab/base-rstudio
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
