name: Docker Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          context: .
          dockerfile: base-scipy/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dddlab/base-scipy
          tag_with_ref: true
          tag_with_sha: true
